# This file generates the GitHub Actions matrix
---
include:
  - board: nice_nano@2.0.0
    shield: think_corney_left nice_view_adapter nice_view
  - board: nice_nano@2.0.0
    shield: think_corney_right nice_view_adapter nice_view
