file_format: "1"
id: think_corney
name: ThinkCorney
type: shield
url: https://github.com/Llirkit/think_corney_num_zmk_config
requires: [pro_micro]
features:
  - keys
  - display
  - studio
siblings:
  - think_corney_left
  - think_corney_right
